### PR TITLE
Fix/#142

### LINKED ISSUE #142: Different Text  /  Texto Diferente
**Explanation:**
The text description below the title is not the same as in the original.

**Current result:**
When you get to the third page, the text below the title says "Enter your ticket number."

**Expected result:**
That when you get to the third page, the text under the title says "Enter the ticket number".

*Screen size:*
All resolutions.

### Screenshots:
Original:
image
Our:
image

### Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the text under the title is correct]

### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46
Our:
 https://github.com/Azordev/maps-project

Spanish Version:

**Explicación:**
La descripción del texto debajo del título no es la misma que en el original.

**Resultado actual:**
Cuando llegue a la tercera página, el texto debajo del título dice "Ingrese su número de boleto".

**Resultado Esperado:**
Que al llegar a la tercera página, el texto debajo del título dice "Ingrese el número de boleto".

*Tamaño de pantalla:*
Todas las resoluciones.

### Capturas de pantalla:
Original:
imagen
Nuestra:
imagen

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[Verifica que el texto debajo del título sea correcto]

### Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46
Nuestra:
https://github.com/Azordev/maps-project

### PR DESCRIPTION
**Pull request by mdrianislam0or1**
### Description

 Different Text / Texto Diferente #142 

#### Screenshots

fix142#1

### CODE REVIEW

**Comment by angelik0828** [comment]
When reviewing the view, the text to be changed was verified, it is in bold!!

**Review by angelik0828 — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Comment by arodriguezl9302** [comment]
@mdrianislam0or1 please resolve conflicts

**Comment by mdrianislam0or1** [comment]
is everything ok @arodriguezl9302 ?

**Comment by arodriguezl9302** [comment]
> is everything ok @arodriguezl9302 ?

yes, merged correctly, good job

**Pull request merged**
