### PR TITLE
fix/#100 height home images

### LINKED ISSUE #100: Home "Aceptar" button is not working in small screens
**Describe the bug**
When I try to click in "Aceptar button" in a screen of 956x635px, it don't work.

I have checked and this happen because the truck and the boy is occupying space of the button and is over it

Please help us to solve this bug without break the home view

**To Reproduce**

1. Go to "Home" (`/`)
2. Open the inspect elements
3. Open the responsive design tool and start to work with the screen size, put a screen size of 900px
4. Try to click the button

**Expected behavior**
When click the button we're redirected to `/check` view

**Screenshots**
imagen
imagen

**Desktop (please complete the following information):**

- OS: Linux Cinnamon
- Browser: Firefox

**Additional context**
I think you could to use z-index to fix it, but if exist a better way it's so better

### PR DESCRIPTION
**Pull request by Eghinner**
### Description

I resolved to center with position absolute and setting a max-height.
I also apply the suggestions of the previous PR #99 

fixes #100

#### Screenshots

responsive

### CODE REVIEW

**Comment by Eghinner** [comment]
Another detail I'm not sure if I should delete the replaced images.
logo
delivery-man

**Review by e-azocar — APPROVED** [review]
@Eghinner Good job

**Comment by e-azocar** [comment]
> Another detail I'm not sure if I should delete the replaced images. logo delivery-man

About delete the not used images, I think should be deleted

**Review by heliomar-pena — APPROVED** [review]
Good work!

**Pull request merged**
